### ISSUE TITLE
Generation 6 Battle Models and onward?

### ISSUE THREAD

**Issue by mxOrbital** [smogon/pokemon-showdown-client#1851] opened 2021-08-08 22:13 UTC
Noticed when connecting to the client, battles in the client are done with DPP Style sprites that aren't animated regardless of which generation the battle is taken plays, specifically ORAS or higher.

Is there a way to make it to it uses the ORAS battle models for gen 6 battles and onward?

**Comment by mia-pi-git** [comment] 2021-08-08 22:16
Do you happen to have the "Use BW sprites instead of XY models" setting checked in the settings tab? (Gear button in the top right.)

**Comment by mxOrbital** [comment] 2021-08-09 09:14
> Do you happen to have the "Use BW sprites instead of XY models" setting checked in the settings tab? (Gear button in the top right.)
> 
> In the future, this sort of question would likely be better for the [Simple Questions](https://www.smogon.com/forums/threads/ask-simple-questions-here-read-original-post-before-posting.3520646/) thread.

I do not, one of the first things i checked.

**Comment by Zarel** [comment] 2021-08-10 14:20
Are you using testclient? I've never bothered actually supporting the models in testclient.

**Comment by mxOrbital** [comment] 2021-08-11 03:23
> Are you using testclient? I've never bothered actually supporting the models in testclient.

Indeed i am, test client hooked to my own showdown server.
Though, it does seem to still be models on my server without the client as well.

**Comment by Karthik99999** [comment] 2021-08-11 13:21
It's cause the 3d models are only used if the dimensions for them are present in `data/pokedex-mini.js`. These dimensions are automatically retrieved by `build-tools/build-minidex`, but the issue is that it needs the actual sprites to be in the sprites directory. Another problem is that regardless of the sprites being there or not, the file is still emitted, meaning the testclient's method of loading the remote data files when the file is not present doesn't work since the file is technically there, it just doesn't have the required data.

**Comment by Zarel** [comment] 2021-10-30 18:41
Yeah, that should be fixable; I just never considered it high priority.

**Comment by mxOrbital** [comment] 2021-11-03 21:46
> Yeah, that should be fixable; I just never considered it high priority.

Is there a way for me to fix this myself currently?

**Comment by Zarel** [comment] 2021-11-07 18:11
I mean, yes, if you can figure it out for yourself. It'd be harder for me to explain to you how to fix it than to just fix it myself, so whenever I have time, I'll fix it myself.

**Comment by mxOrbital** [comment] 2021-11-21 01:21
> I mean, yes, if you can figure it out for yourself. It'd be harder for me to explain to you how to fix it than to just fix it myself, so whenever I have time, I'll fix it myself.

You know of anyone who fixed it themselves or do you mind explaining it? i have the time and would be willing to do it on my own rather than wait for a fix.

**Closed** 2021-11-21 21:19 UTC

**Comment by Zarel** [comment] 2021-11-21 21:58
If someone had fixed it themselves they would probably have PRed it and we wouldn't be having this conversation. :p

Anyway, I handled it. If you couldn't understand @Karthik99999's explanation, maybe the commit itself would make it clearer?

**Comment by mxOrbital** [comment] 2021-11-22 01:19
> If someone had fixed it themselves they would probably have PRed it and we wouldn't be having this conversation. :p
> 
> Anyway, I handled it. If you couldn't understand @Karthik99999's explanation, maybe the commit itself would make it clearer?

Nice. How do i update my client again? been a minute since i've used this.
